# Generated by Django 2.2.2 on 2019-08-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('animePageLink', models.TextField()),
                ('pageNum', models.IntegerField()),
                ('coverLink', models.TextField()),
                ('yearProd', models.IntegerField()),
                ('rates', models.DecimalField(decimal_places=1, max_digits=10)),
                ('types', models.TextField(null=True)),
                ('story', models.TextField()),
            ],
        ),
    ]
